defmodule SquirrelixErrorFormatTest do
  use ExUnit.Case, async: true

  alias Squirrelix.Error
  alias Squirrelix.Error.CannotOverwriteFile
  alias Squirrelix.Error.CannotReadFile
  alias Squirrelix.Error.CannotWriteFile
  alias Squirrelix.Error.InvalidQueryMetadataFile
  alias Squirrelix.Error.MissingQueryMetadata
  alias Squirrelix.Error.MissingQueryMetadataField
  alias Squirrelix.Error.OutdatedFile
  alias Squirrelix.Error.UnsupportedPostgresType

  test "format_outdated_file_error matches upstream Squirrel wording" do
    formatted = Error.format(%OutdatedFile{file: "lib/app/sql.ex"})

    assert formatted =~ "Error: Outdated file"
    assert formatted =~ "lib/app/sql.ex is outdated"
    assert formatted =~ "mix squirrelix.gen"
  end

  test "format_cannot_overwrite_file_error matches upstream Squirrel wording" do
    formatted = Error.format(%CannotOverwriteFile{file: "lib/app/sql.ex"})

    assert formatted =~ "Error: Cannot overwrite file"
    assert formatted =~ "was not generated by Squirrelix"
    assert formatted =~ "Hint: Rename the file and run `mix squirrelix.gen` again."
  end

  test "format_cannot_read_file_error is structured with posix reason" do
    formatted =
      Error.format(%CannotReadFile{file: "lib/accounts/sql/get_user.sql", reason: :enoent})

    assert formatted =~ "Error: Cannot read file"
    assert formatted =~ "lib/accounts/sql/get_user.sql"
    assert formatted =~ "no such file or directory"
    refute formatted =~ "%Squirrelix.Error.CannotReadFile"
  end

  test "format_cannot_write_file_error is structured with posix reason" do
    formatted = Error.format(%CannotWriteFile{file: "lib/accounts/sql.ex", reason: :eacces})

    assert formatted =~ "Error: Cannot write to file"
    assert formatted =~ "lib/accounts/sql.ex"
    assert formatted =~ "permission denied"
    refute formatted =~ "%Squirrelix.Error.CannotWriteFile"
  end

  test "format_missing_query_metadata_error includes actionable hint" do
    formatted = Error.format(%MissingQueryMetadata{file: "lib/accounts/sql/get_user.sql"})

    assert formatted =~ "Error: Missing query metadata"
    assert formatted =~ "lib/accounts/sql/get_user.sql"
    assert formatted =~ "Hint:"
    assert formatted =~ "squirr_elix.exs"
    assert formatted =~ "--infer"
    refute formatted =~ "%Squirrelix.Error.MissingQueryMetadata"
  end

  test "format_missing_query_metadata_field_error names the missing field" do
    formatted =
      Error.format(%MissingQueryMetadataField{
        file: "lib/accounts/sql/get_user.sql",
        field: :returns
      })

    assert formatted =~ "Error: Incomplete query metadata"
    assert formatted =~ "lib/accounts/sql/get_user.sql"
    assert formatted =~ "`returns`"
    assert formatted =~ "Hint:"
    assert formatted =~ "params"
    refute formatted =~ "%Squirrelix.Error.MissingQueryMetadataField"
  end

  test "format_invalid_query_metadata_file_error explains evaluation failure" do
    formatted =
      Error.format(%InvalidQueryMetadataFile{file: "squirr_elix.exs", reason: :not_a_map})

    assert formatted =~ "Error: Invalid query metadata file"
    assert formatted =~ "squirr_elix.exs"
    assert formatted =~ "map"
    assert formatted =~ "Hint:"
    refute formatted =~ "%Squirrelix.Error.InvalidQueryMetadataFile"
  end

  test "format_unsupported_type_error includes optional hints" do
    formatted =
      Error.format(%UnsupportedPostgresType{
        name: "custom_type",
        hint: "Try using a supported built-in instead."
      })

    assert formatted =~ "Error: Unsupported type"
    assert formatted =~ "`custom_type`"
    assert formatted =~ "Hint: Try using a supported built-in instead."
  end

  test "format_unsupported_type_error surfaces composite policy hints from TypeMapper" do
    assert {:error, error} =
             Squirrelix.TypeMapper.from_postgres("inventory_item", kind: "c")

    formatted = Error.format(error)

    assert formatted =~ "Error: Unsupported type"
    assert formatted =~ "`inventory_item`"
    assert formatted =~ "Hint:"
    assert formatted =~ "composite"
  end

  test "format_unsupported_type_error surfaces range rejection hints" do
    assert {:error, error} = Squirrelix.TypeMapper.from_postgres("int4range")
    formatted = Error.format(error)

    assert formatted =~ "Error: Unsupported type"
    assert formatted =~ "`int4range`"
    assert formatted =~ "Hint:"
    assert formatted =~ "range"
  end
end
