defmodule SquirrelixErrorFormatTest do
  use ExUnit.Case, async: true

  alias Squirrelix.Error
  alias Squirrelix.Error.CannotOverwriteFile
  alias Squirrelix.Error.OutdatedFile
  alias Squirrelix.Error.UnsupportedPostgresType

  test "format_outdated_file_error matches upstream Squirrel wording" do
    formatted = Error.format(%OutdatedFile{file: "lib/app/sql.ex"})

    assert formatted =~ "Error: Outdated file"
    assert formatted =~ "lib/app/sql.ex is outdated"
    assert formatted =~ "mix squirrelix.gen"
  end

  test "format_cannot_overwrite_file_error matches upstream Squirrel wording" do
    formatted = Error.format(%CannotOverwriteFile{file: "lib/app/sql.ex"})

    assert formatted =~ "Error: Cannot overwrite file"
    assert formatted =~ "was not generated by Squirrelix"
    assert formatted =~ "Hint: Rename the file and run `mix squirrelix.gen` again."
  end

  test "format_unsupported_type_error includes optional hints" do
    formatted =
      Error.format(%UnsupportedPostgresType{
        name: "custom_type",
        hint: "Try using a supported built-in instead."
      })

    assert formatted =~ "Error: Unsupported type"
    assert formatted =~ "`custom_type`"
    assert formatted =~ "Hint: Try using a supported built-in instead."
  end

  test "format_unsupported_type_error surfaces composite policy hints from TypeMapper" do
    assert {:error, error} =
             Squirrelix.TypeMapper.from_postgres("inventory_item", kind: "c")

    formatted = Error.format(error)

    assert formatted =~ "Error: Unsupported type"
    assert formatted =~ "`inventory_item`"
    assert formatted =~ "Hint:"
    assert formatted =~ "composite"
  end

  test "format_unsupported_type_error surfaces range rejection hints" do
    assert {:error, error} = Squirrelix.TypeMapper.from_postgres("int4range")
    formatted = Error.format(error)

    assert formatted =~ "Error: Unsupported type"
    assert formatted =~ "`int4range`"
    assert formatted =~ "Hint:"
    assert formatted =~ "range"
  end
end
