defmodule SquirrElixErrorFormatTest do
  use ExUnit.Case, async: true

  alias SquirrElix.Error
  alias SquirrElix.Error.CannotOverwriteFile
  alias SquirrElix.Error.OutdatedFile
  alias SquirrElix.Error.UnsupportedPostgresType

  test "format_outdated_file_error matches upstream Squirrel wording" do
    formatted = Error.format(%OutdatedFile{file: "lib/app/sql.ex"})

    assert formatted =~ "Error: Outdated file"
    assert formatted =~ "lib/app/sql.ex is outdated"
    assert formatted =~ "mix squirr_elix.gen"
  end

  test "format_cannot_overwrite_file_error matches upstream Squirrel wording" do
    formatted = Error.format(%CannotOverwriteFile{file: "lib/app/sql.ex"})

    assert formatted =~ "Error: Cannot overwrite file"
    assert formatted =~ "was not generated by SquirrElix"
    assert formatted =~ "Hint: Rename the file and run `mix squirr_elix.gen` again."
  end

  test "format_unsupported_type_error includes optional hints" do
    formatted =
      Error.format(%UnsupportedPostgresType{
        name: "custom_type",
        hint: "Try using a supported built-in instead."
      })

    assert formatted =~ "Error: Unsupported type"
    assert formatted =~ "`custom_type`"
    assert formatted =~ "Hint: Try using a supported built-in instead."
  end
end
