defmodule Squirrelixir do
  @moduledoc """
  Compatibility-focused Elixir reimplementation of selected Squirrel behavior.
  """

  @generated_module_marker "> 🐿️ This module was generated automatically using"
  @generated_function_marker "> 🐿️ This function was generated automatically using"
  @generated_module_marker_ascii "> This module was generated automatically using"
  @generated_function_marker_ascii "> This function was generated automatically using"

  @doc """
  Classifies file content to determine whether it was likely generated by Squirrel.
  """
  @spec classify_file_content(String.t()) :: :likely_generated | :empty | :not_generated
  def classify_file_content(content) when is_binary(content) do
    likely_generated? =
      String.contains?(content, @generated_module_marker) or
        String.contains?(content, @generated_function_marker) or
        String.contains?(content, @generated_module_marker_ascii) or
        String.contains?(content, @generated_function_marker_ascii)

    cond do
      likely_generated? -> :likely_generated
      String.trim(content) == "" -> :empty
      true -> :not_generated
    end
  end

  @doc """
  Compares two code snippets ignoring comments and whitespace.
  """
  @spec compare_code_snippets(String.t(), String.t()) :: :same | :different
  def compare_code_snippets(actual_code, expected_code)
      when is_binary(actual_code) and is_binary(expected_code) do
    if tokenize(actual_code) == tokenize(expected_code) do
      :same
    else
      :different
    end
  end

  @spec tokenize(String.t()) :: [String.t()]
  defp tokenize(code) do
    chars = String.to_charlist(code)

    chars
    |> do_tokenize(:normal, [], [])
    |> Enum.reverse()
  end

  defp do_tokenize([], :normal, current, tokens), do: maybe_push(current, tokens)
  defp do_tokenize([], :line_comment, current, tokens), do: maybe_push(current, tokens)
  defp do_tokenize([], :string, current, tokens), do: maybe_push(current, tokens)

  defp do_tokenize([?/, ?/ | rest], :normal, current, tokens) do
    tokens = maybe_push(current, tokens)
    do_tokenize(rest, :line_comment, [], tokens)
  end

  defp do_tokenize([?# | rest], :normal, current, tokens) do
    tokens = maybe_push(current, tokens)
    do_tokenize(rest, :line_comment, [], tokens)
  end

  defp do_tokenize([char | rest], :line_comment, current, tokens) do
    if char == ?\n do
      do_tokenize(rest, :normal, current, tokens)
    else
      do_tokenize(rest, :line_comment, current, tokens)
    end
  end

  defp do_tokenize([?" | rest], :normal, current, tokens) do
    tokens = maybe_push(current, tokens)
    do_tokenize(rest, :string, [?"], tokens)
  end

  defp do_tokenize([?\\, escaped | rest], :string, current, tokens) do
    do_tokenize(rest, :string, [escaped, ?\\ | current], tokens)
  end

  defp do_tokenize([?" | rest], :string, current, tokens) do
    token = [?" | Enum.reverse(current)]
    do_tokenize(rest, :normal, [], [List.to_string(token) | tokens])
  end

  defp do_tokenize([char | rest], :string, current, tokens) do
    do_tokenize(rest, :string, [char | current], tokens)
  end

  defp do_tokenize([char | rest], :normal, current, tokens) when char in [32, 9, 10, 13] do
    tokens = maybe_push(current, tokens)
    do_tokenize(rest, :normal, [], tokens)
  end

  defp do_tokenize([char | rest], :normal, current, tokens) do
    char_string = <<char::utf8>>

    cond do
      identifier_char?(char) ->
        do_tokenize(rest, :normal, [char | current], tokens)

      true ->
        tokens = maybe_push(current, tokens)
        do_tokenize(rest, :normal, [], [char_string | tokens])
    end
  end

  defp maybe_push([], tokens), do: tokens

  defp maybe_push(current, tokens) do
    [current |> Enum.reverse() |> List.to_string() | tokens]
  end

  defp identifier_char?(char) do
    (char >= ?a and char <= ?z) or
      (char >= ?A and char <= ?Z) or
      (char >= ?0 and char <= ?9) or
      char in [?_]
  end
end
